#+STARTUP overview
#+TITLE: The Org Manual(Org 手册)
#+CATEGORY: 手册, 翻译
#+URL： https://orgmode.org/org.html
* Introduction
- Summary: Brief summary of what Org does. 摘要：关于 Org 可以用来做什么的简明摘要.
- Installation: Installing Org. 安装：安装 Org.
- Activation: How to activate Org for certain buffers. 激活：如何在特定缓存中激活 Org.
- Feedback: Bug reports, ideas, patches, etc. 反馈：错误，想法，补丁等等.
- Conventions: Typesetting conventoins used in this manual. 惯例：手册中使用的排版惯例
** Summary 摘要
Org is a mode for keeping notes, maintaining TODO lists, and project planning with a fast and effective plain-text markup language. It also is an authoring system with unique support for literate programing and reproducible research.

Org 是用来记笔记，维护 TODO 列表和项目计划的 Mode，它是一个快速，高效文本式标记语言。它也是一个创作系统，带有唯一的文学编程和可重复性研究。

Org is implemented on top of Outline mode, which makes it possible to keep the content of large files well structured. Visibility cycling and structure editing help to work with the tree. Tables are easily created with a built-in table editor. Plain text URL-like links connect to websites, emails Usenet messages, BBDB entries and any files related to the projects.

Org 实现了 Outline mode，这让它有可能保持对大文件有好的结构化表现。可视化的循环和结构化的编辑有助于以树状结构的工作。内嵌的 table 编辑器可以轻松地创建出 table。形如 URL 的文本可以链接到网站、Email、消息，项目相关的任何文件。

Org develops organizational tasks around notes files that contain lists or information about projects as plain text. Project planning and task management make use of metadata which is part of an outline node. Based on this data, specific entries can be extracted in queries and create dynamic /agenda views/ that also integrate the Emacs calendar and diary. Org can be used to implement many different project planning schemas, such as David Allen's GTD system.

Org 围绕注释文件开发组织任务，这些文件以文本形式包含项目的列表和信息。项目计划和任务管理利用 metadata（元数据），而元数据是大纲结点的一部分。基于这些数据，特殊的入口可以被解析为查询和创建动态 /议事视图/，它们同样集成了 Emacs 的日历和日记。Org 可以用来实现不同的项目规划方案，如 xxx。

Org files can serve as a single source authoring system with export to many different formats such as HTML, LaTeX, Open Document, and Markdown. New export backends can be derived from existing ones, or defined from scratch.

Org 文件可以用作于单一源码创作系统，可以导出成不同格式的文件，如 HTML，LaTeX, Open Document, 和 Markdown。新的导出可以源自已经存在的或者从 0 开始。

Org files can include source code blocks, which makes Org uniquely suited for authoring technical documents with code examples. Org source code blocks are fully functional; they can be evaluated in place and their results can be captured in the file. This makes it possible to create a single file reproducible research compendium.
