#+STARTUP overview
#+TITLE: The Org Manual(Org 手册)
#+CATEGORY: 手册, 翻译
#+AUTHOR: 李超
#+URL： https://orgmode.org/org.html
* Introduction
- Summary: Brief summary of what Org does. 摘要：关于 Org 可以用来做什么的简明摘要.
- Installation: Installing Org. 安装：安装 Org.
- Activation: How to activate Org for certain buffers. 激活：如何在特定缓存中激活 Org.
- Feedback: Bug reports, ideas, patches, etc. 反馈：错误，想法，补丁等等.
- Conventions: Typesetting conventoins used in this manual. 惯例：手册中使用的排版惯例
** Summary 摘要
Org is a mode for keeping notes, maintaining TODO lists, and project planning with a fast and effective plain-text markup language. It also is an authoring system with unique support for literate programing and reproducible research.

Org 是用来记笔记，维护 TODO 列表和项目计划的 Mode，它是一个快速，高效文本式标记语言。它也是一个创作系统，带有唯一的文学编程和可重复性研究。

Org is implemented on top of Outline mode, which makes it possible to keep the content of large files well structured. Visibility cycling and structure editing help to work with the tree. Tables are easily created with a built-in table editor. Plain text URL-like links connect to websites, emails Usenet messages, BBDB entries and any files related to the projects.

Org 实现了 Outline mode，这让它有可能保持对大文件有好的结构化表现。可视化的循环和结构化的编辑有助于以树状结构的工作。内嵌的 table 编辑器可以轻松地创建出 table。形如 URL 的文本可以链接到网站、Email、消息，项目相关的任何文件。

Org develops organizational tasks around notes files that contain lists or information about projects as plain text. Project planning and task management make use of metadata which is part of an outline node. Based on this data, specific entries can be extracted in queries and create dynamic /agenda views/ that also integrate the Emacs calendar and diary. Org can be used to implement many different project planning schemas, such as David Allen's GTD system.

Org 围绕注释文件开发组织任务，这些文件以文本形式包含项目的列表和信息。项目计划和任务管理利用 metadata（元数据），而元数据是大纲结点的一部分。基于这些数据，特殊的入口可以被解析为查询和创建动态 /议事视图/，它们同样集成了 Emacs 的日历和日记。Org 可以用来实现不同的项目规划方案，如 xxx。

Org files can serve as a single source authoring system with export to many different formats such as HTML, LaTeX, Open Document, and Markdown. New export backends can be derived from existing ones, or defined from scratch.

Org 文件可以用作于单一源码创作系统，可以导出成不同格式的文件，如 HTML，LaTeX, Open Document, 和 Markdown。新的导出可以源自已经存在的或者从 0 开始。

Org files can include source code blocks, which makes Org uniquely suited for authoring technical documents with code examples. Org source code blocks are fully functional; they can be evaluated in place and their results can be captured in the file. This makes it possible to create a single file reproducible research compendium.

Org 文件可以包含代码块，这让 Org 成为了特别适用于创作带有代码样例的技术文档。Org 的代码块功能强悍，他们可以就地执行而且也可以可以在文件中获取结果。这让创建一个可复制研究概要成为可能。

Org keeps simple things simple. When first fired up, it should feel like a straightforward, easy to use outliner. Complexity is not imposed, but a large amount of functionality is available when needed. Org is a toolbox. Many users actually run only a -very personal- fraction of Org's capabilities, and know that there is more whenever they need it.

Org 让简单的事情保持简单。当刚开始使用时，它让你感觉是一个直接且简单的大纲列表。不强加复杂性，但是有大量的功能可用。Org 像是一个工具箱。很多人实际上只运行 Org 强大能力中的个人了解的一部分，要了解 Org 有更多功能，需要时即可使用。

All of this is achieved with strictly plain text files, the most portable and future-proof file format. Org runs in Emacs. Emacs is one of the most widely ported programs, so that Org mode is available on every major platform.

所有这些都是通过严格的文本文件实现的，文本文件是最可移植和最有前瞻性的文件格式。Org 运行在 Emacs 中。Emacs 是使用最广泛的可移植性程序，所有 Org mode 可以在所有主流平台获取到。

There is a website for Org which provides links to the newest version of Org, as well as additional information, frequently asked questions(FAQ), links to tutorials, etc. This page is located at https://orgmode.org.

有一个 Org 的网站，提供 Org 的最新版本，也有最新的消息，常见问题（FAQ），教程的链接等等。当前页面的网址是：https://orgmode.org.

An earlier version (7.3) of this manual is available as a _paperback book from Network Theory Ltd_.  更早版本（7.3）的手册可以在 xxx 获取到。
** Installation 安装
Org is included in all recent distributions of GNU Emacs, so you probably do not need to install it. Most users will simply activate Org and begin exploring its many features.

Org 在最近的 GNU Emacs 中都有的，所以你应该不需要安装它。很多人会简单的使用 Org 且开始研究它的一些特性。

If, for one reason or another, you want to install Org on top of this pre-packaged version, there are three ways to do it:

如果，由于某种原因，你想安装 Org，有三种方式：

 - by using the Emacs package system: 使用 Emacs 的包管理
 - by downloading Org as an archive; or 下载 Org 安装包
 - by using Org's git repository. 使用 Org 的 git 库
We *strongly recommend* sticking to a single installation method.

我们强烈建议坚持使用一种安装方法。

*Using Emacs packaging system* *使用 Emacs 包管理*

Recent Emacs distributions include a packaging system which lets you install Elisp libraries. You can install Org with /M-x package-install RET org/.

最近的 Emacs 版本包括了一个包系统，它可以让你安装 Elisp 的包。你可以用命令 /M-x package-insntall RET org/ 来安装 Org。

  *Important:* You need to do this in a session where no '.org' file has been visited. i.e., where no Org built-in function have been loaded.
  Otherwise autoload Org functions will mess up the installation.

  *重点:* 在没有'.org'的文件被访问过时，你需要在一个会话中做。例如，Org 的内部方法还没有被加载。否则，自动加载 Org 方法会扰乱安装。

If you want to use Org's package repository, check out the _Org ELPA page_. 如果你要用 Org 的库，访问 _Org ELPA_ 页面。

*Downloading Org as an archive* *下载 Org 安装包*

You can download Org latest release from _Org's website_. In this case, make sure you set the load-path correctly in your Emacs init file:

你可以从 _Org's 网站_ 下载 Org 的最新发布版本。这种情况下，你要确保你 Emacs 初始化文件里的 load-path 的设置是正确的。

<e


